### ISSUE TITLE
発表資料（途中）

### ISSUE THREAD

**Issue by shuntaNak** [rkclhack/hackathon-ta-A#4]
まだ穴あき状態ですが発表資料をつくりました。
使った方が良さそうなら是非！
[hackathon 資料.pptx](https://github.com/rkclhack/hackathon-ta-A/files/950514/hackathon.pptx)

**Comment by shuntaNak** [comment]
[hackathon 資料revision#1.pptx](https://github.com/rkclhack/hackathon-ta-A/files/950537/hackathon.revision.1.pptx)

**Comment by shuntaNak** [comment]
[hackathon 資料revision#2.pptx](https://github.com/rkclhack/hackathon-ta-A/files/950608/hackathon.revision.2.pptx)

**Comment by Liuhei** [comment]
ありがとうございます
助かります🙌

**Comment by shuntaNak** [comment]
[hackathon 資料revision#3.pptx](https://github.com/rkclhack/hackathon-ta-A/files/957129/hackathon.revision.3.pptx)

**Comment by fffukami** [comment]
[hackathon.revision.4.key.zip](https://github.com/rkclhack/hackathon-ta-A/files/957994/hackathon.revision.4.key.zip)

**Comment by shuntaNak** [comment]
[hackathon 資料revision#5.pptx](https://github.com/rkclhack/hackathon-ta-A/files/958025/hackathon.revision.5.pptx)
